### ISSUE TITLE
March 2025 - Album art

### ISSUE THREAD

**Issue by mattl** [foocorp/hacienda#68]
A new issue for any issues with the album art feature.

You should see album art only when browsing an album of an artist.

For example: https://libre.fm/artist/Half+Man+Half+Biscuit/album/Achtung+Bono

**Comment by tonieee** [comment]
This album seems to have a broken link to the image:

https://libre.fm/artist/Shop+Assistants/album/Shop+Assistants

This album is showing no image at all:

https://libre.fm/artist/Black+Tambourine/album/Black+Tambourine

I can find images for both in the cover art archive:

https://coverartarchive.org/release/87d53dfc-0c03-44b4-b746-f69e541460fe/36630525510-250.jpg

https://coverartarchive.org/release/6541a365-b131-4e75-a434-ec5d4f402ba8/7940010259-250.jpg

This is a great new feature though! Thank you!

**Comment by mattl** [comment]
So, the first album -- https://musicbrainz.org/release/2b62c883-7da7-4c6d-bc15-208f35e44a5e is the release we're getting from the API. 

As you can see on the right, there's no image associated with that. 

You should be able to make a MusicBrainz account and update that first album to use that artwork. I need to try that myself, so will you try it and report back on how easy it is? When an image fails, it would be nice to have a way to make that clearer.

**Comment by mattl** [comment]
For the second band, you'll note the page says "Black tamborine" at the top... I'm trying to figure this out right now. The way it picks an artist is that the first time it's scrobbled I believe it picks that one. Trying to double check and fix that a bit now.

**Comment by tonieee** [comment]
Thank you for the quick response. I've updated for the Shop Assistants album on MusicBrainz - I believe it takes some time for the image to become available in the cover art archive so hopefully it will appear soon.

However, I have found a more pedantic example where the image is for a specific version of the release with a sticker on the front:

https://libre.fm/artist/Carole+King/album/Tapestry

For both this album and the Shop Assistants, the release group shows the correct image. Could it be possible to get the image from the release group instead? I don't know if that's possible with the MusicBrainz api or too much work but it would solve both and potentially other similar problems.

**Comment by tonieee** [comment]
The Shop Assistants album is showing the image now 😁

**Comment by mattl** [comment]
Awesome!

Now I'm requesting the CD format when I search... hoping that'll help.

**Comment by mattl** [comment]
Now working on tracks too if the track is part of an album..

https://libre.fm/artist/Playboi+Carti/album/Whole+Lotta+Red/track/New+N3on

**Comment by mattl** [comment]
> However, I have found a more pedantic example where the image is for a specific version of the release with a sticker on the front:
> 
> https://libre.fm/artist/Carole+King/album/Tapestry

I've just erased the MBID in the database for this, hoping it'll now pick a better one next time.

It looks like it worked.

**Comment by tonieee** [comment]
> > However, I have found a more pedantic example where the image is for a specific version of the release with a sticker on the front:
> > https://libre.fm/artist/Carole+King/album/Tapestry
> 
> I've just erased the MBID in the database for this, hoping it'll now pick a better one next time.
> 
> It looks like it worked.

It looks like it's linking to an album of the same name by a different artist now.

Black Tambourine is showing the correct image now though!

**Comment by mattl** [comment]
Added album art to now playing... https://libre.fm/user/mattl and to the single scrobbles https://libre.fm/user/mattl/scrobble/1741301354

@tonieee Carole King should be fixed shortly.

**Comment by mattl** [comment]
Look for a "debugging" dropbox/details field on album and track pages with a debug link if you're curious.

**Comment by tonieee** [comment]
The Carole King is still showing the sticker for the "legacy edition". I guess this is not something that will be easy to solve as there's probably not an easy way to say which version of the release has the "correct" artwork to show. In some cases there might not even be one correct version for albums that have multiple alternative covers. Just having an album version is good though.

However, I'm not sure that the change to restrict to just the CD is working. I have listened to a few today that don't have a CD release but have images stored against the vinyl or digital release. But libre.fm is showing no image and no link to MusicBrainz.

For example this album:

https://libre.fm/artist/Fightmilk/album/Not+With+That+Attitude

It has a digital release with artwork here:

https://musicbrainz.org/release/6cfd8d20-db32-4f1f-a5b1-b7e54164989d

**Comment by mattl** [comment]
Thanks for helping to look into this.

When I try to search that one without the CD format, I get the vinyl which also doesn't have artwork. 

I've just updated the database manually for the Carole King album. We do cache the pages pretty aggressively but I'll check again later and see if that fixes it.

**Comment by tonieee** [comment]
> Thanks for helping to look into this.

It's no problem at all. Thank you for building this! 

> When I try to search that one without the CD format, I get the vinyl which also doesn't have artwork.

I've added the artwork for the vinyl release from discogs so that is showing now.

> I've just updated the database manually for the Carole King album. We do cache the pages pretty aggressively but I'll check again later and see if that fixes it.

That looks great now. Thank you!

Doing this manually for every release is probably going to be too much though.

Is it possible to get the artwork from the release group with the API you're using? The release group page always show an image from one of the releases - I don't know how it's chosen so it could sometimes have a less ideal one but at least it would always have an image if at least one release had one.

For example, here is the release group page for the Fightmilk album:

https://musicbrainz.org/release-group/5917fe44-4ee3-4500-b735-aaac0795f50b

**Comment by tonieee** [comment]
Also linking to the release group in musicbrainz might make more sense than linking to a random specific these if it's possible.

**Comment by mattl** [comment]
Okay, a bunch of work on this tonight. 

Notes:

MBID = MusicBrainz ID aka a number like 5917fe44-4ee3-4500-b735-aaac0795f50b

* Release groups are in, which means I had to wipe all the data we'd stored on album MBIDs. Around 50,000 of them. We should get that data back in a few days of people using the site.
* I'm working on a bulk update that I'll try and run tomorrow
* Release groups also let us snag the MBID for the artist. We have quite a few of these but plenty more missing.

Thanks @tonieee -- please let me know if you find any examples of things not working

**Comment by tonieee** [comment]
Thanks Matt. The album art is good for every album I've looked at.

Unfortunately the MusicBrainz links now seem to be broken on every page. I think you are using the release URL with the release-group id. If I change the url it shows the correct page.

For example, the Tapestry page links to here:

https://musicbrainz.org/release/6e4f39e6-3403-39d7-81c6-8e61a990d509

which gives a "Release not found" message but if I change it to:

https://musicbrainz.org/release-group/6e4f39e6-3403-39d7-81c6-8e61a990d509

I get the correct release group page.

**Comment by mattl** [comment]
Yep that sounds 100% like I forgot to update that link. I’ll get that fixed.

**Comment by mattl** [comment]
@tonieee Okay, artist pages now link to MusicBrainz. I'm also pulling all the other artist links from MusicBrainz too. I need to write some more code to make them have more attractive/useful labels, but this okay for now.

https://libre.fm/artist/Carole+King/ will show you 

<img width="557" alt="Carole King profile on Libre.fm" src="https://github.com/user-attachments/assets/1a3090e3-27f7-455e-8cf9-b88b1993d784" />

**Comment by tonieee** [comment]
That's brilliant Matt!

The artist links to MusicBrainz are not working though - they're linking back to libre.fm. Carole King is to:

https://libre.fm/artist/Carole+King/%3Ca%20href=

The "Add/edit links on MusicBrainz" links are good.

**Comment by mattl** [comment]
Link fixed! I had a link inside a link.

Also, check https://libre.fm/artist/Carole+King/ again now.

Artist images from Wikipedia!

**Comment by tonieee** [comment]
The links work now. And artists images are looking good. But the Carole King page is now showing "Artist not found" 😞

**Comment by mattl** [comment]
Yes, I see the Carole King bug... fixing.

**Comment by mattl** [comment]
Carole King is fixed... as I'm adding data from MusicBrainz, some of the names got messed up... "Carole King" became "King, Carole" -- this is all set for Carole King and The Cure, but I'll keep looking for others.

**Comment by mattl** [comment]
We now have... biographies of the artists and some Wikipedia photos too. 

Stuff that doesn't work yet: 

- if the artist has "(band)" or anything like that in their Wikipedia page URL. 

- artist bios are pulled in once from the Last FM wiki and then we grab the first paragraph. We only do this if we have the musicbrainz ID for the artist. 

But... Carole King's page loads and has biography info. And so does Half Man Half Biscuit..

**Comment by tonieee** [comment]
That's looking really good - thanks Matt

**Comment by mattl** [comment]
So a lot of the artists are back and the album art search continues. 

Today I added album art to the the artist page. 

Screenshots of Carole King, HMHB and Radiohead (they have a LOT of albums) pages.

![Image](https://github.com/user-attachments/assets/d91a9e8e-0919-4ea4-bbcb-784860f591c3)
![Image](https://github.com/user-attachments/assets/64cc900b-c657-40ff-9c42-1301a4905417)
![Image](https://github.com/user-attachments/assets/d95f9bef-a9ce-4db9-932e-bb3d17432bd0)

**Comment by mattl** [comment]
Today I fixed some performance issues across the site, which broke things for a moment but I think they're fixed again (See #70 )

The homepage, user pages, user scrobble pages, user recaps and all pages starting with /artist are now cached.

User pages are only cached for a couple minutes. Everything else is cached between 5 mins and 6 months (user scrobbles, yearly recaps)

**Comment by RivenSkaye** [comment]
I'm noticing that some artists and albums can have problems fetching Musicbrainz data such as album art and similar - with an error about no MB ID being found. 

Example that got me here: [Shiena Nishizawa - New Generation on Meteor/New Generation](https://libre.fm/artist/Shiena+Nishizawa/album/Meteor%252FNew+Generation/track/New+Generation)

The debug link `https://turtle.libre.fm/cover.php?album=Meteor%2FNew%20Generation&artist=SHIENA%20NISHIZAWA&stop=1` provides `https://musicbrainz.org/ws/2/release-group?query=Meteor%2FNew+Generation%20AND%20artist%3a%28SHIENA+NISHIZAWA%29&limit=1&fmt=json` (followed by some JSON payload, but stripping that allows requests to work in the browser as well) for the search. The correct release is found when leaving the artist out, or when using the 1:1 matching artist name in whatever form is listed on MB [(西沢幸奏)](https://musicbrainz.org/artist/a5b3dd54-a329-472d-b4e5-081591c79ca5). It also works when using the Artist ID parameter (`arid`) instead.

I know you have to deal with whatever name scrobblers pass on, but is it perhaps an idea to let users add (or propose) MB IDs for artists or albums on the relevant pages, at least if none are known? Using the artist ID parameter (`arid%3a(a5b3dd54-a329-472d-b4e5-081591c79ca5)`) instead works flawlessly and those could relatively easily be bound to multiple artist names (which would also unify some aliases and name changes)

**Comment by mattl** [comment]
So there’s a script running that’s trying to find MusicBrainz IDs for all the other artists. This runs approximately every 2-3 minutes and pulls up between 30 and 50 artists each time. 

In the few weeks I’ve been running this I’ve already managed to get Musicbrainz IDs for around 600,000 artists. 

I’ll spend some time early next week getting the script to output some better status updates that I can share here.

**Comment by denmch** [comment]
Thanks for making this. I can't imagine the effort or the cost to maintain it.

I have kind of a funny one here, in that the album art is completely unrelated and could have been a campy prank if it weren't an accident. A radio station on scrobblerad.io played the Plan by Built to Spill, from the album Keep it Like a Secret, evidently with malformed data.

Web Scrobbler identified the song as follows:
- Cover art: from the album Built to Spill by artist Scarlet Rae (incorrect, from coverartarchive.org)
- Track name: 01 the plan (malformed: includes track number, lowercase)
- Track artist: Built to Spill (correct!)
- Album name: 01 the plan (incorrect, of course!)

<img width="208" alt="Screenshot from Web Scrobbler showing the wrong album cover for a song." src="https://github.com/user-attachments/assets/d1154dfd-ccc9-4b47-81cc-88d04117a2e5" />

Libre.fm concurred, except in the case of the album art:
- Cover art: Planet of the Vaginas by Porn to Hula (incorrect, from Musicbrainz)

<img width="292" alt="Screenshot from JadeRadar's Libre.fm history showing the wrong album cover for a song." src="https://github.com/user-attachments/assets/f2f9f87c-023d-4165-9afa-75f89c6d601c" />

[My recent playlist](https://libre.fm/user/JadeRadar) and the [track page](https://libre.fm/artist/Built+to+Spill/track/01+the+plan) for the incorrectly named song both correctly identify the band as Built to Spill, but the album link points to Planet of the Vaginas. If you visit [my scrobble for this track](https://libre.fm/user/JadeRadar/scrobble/1742569122), and click the name of the song and then click to see it on Musicbrainz, you'll see that "01 the plan" links to Planet of the Vaginas.

It's not clear to me how that association was made on the Libre.fm side. I can't find a search with the available terms that would make the two. With the available data, the album cover search should have been allowed to fail rather than land on the wrong title by the wrong artist.

I reckon that if I had been monitoring Web Scrobbler and editing the track as it played this could have been avoided, but it's less than ideal to closely monitor the scrobbler while casually listening, and we should have the ability to at least delete scrobbles. Ideally we could edit as well, though deleting would suffice to minimize bad data.

Thanks again, and best of luck.

**Comment by denmch** [comment]
> Where are you scrobbling this song from? I’ll check it all out.

I stumbled across https://scrobblerad.io/ while looking for radio stations that would work well with Web Scrobbler. 

Unfortunately, I was clicking on random stations to see what was available, and didn't catch which station it was. But here's the scrobble metadata from my Web Scrobbler cache of successful scrobbles showing how Web Scrobbler identified the track:

```html
<div class="_scrobble_1naa3_227">
  <img class="_coverArt_1naa3_517" src="https://coverartarchive.org/release/9925e22a-6214-46c0-b137-6bf77385d7c7/front-500">
  <div class="_scrobbleDetails_1naa3_522">
    <div class="_scrobbleMetadata_1naa3_531">
      <span class="_trackName_1naa3_538">01 the plan</span>
      <span class="_artistName_1naa3_542">Built to Spill</span>
      <span class="_albumName_1naa3_543">01 The Plan</span>
      <span class="_albumArtistName_1naa3_544"></span>
    </div>
    <div class="_scrobbleActions_1naa3_547">
      <button class="_scrobbleActionButton_1naa3_551">Remove</button>
    </div>
  </div>
  <span class="_scrobbleDate_1naa3_594" title="3/21/2025, 7:58:42 AM">3 hours ago</span>
</div>
```
